<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kingfisher_bringup</name>
  <version>0.0.0</version>
  <description>Cross-package launch compositions for the Kingfisher ASV.</description>
  <maintainer email="luis.batista@gatech.edu">Luis Felipe Wolf Batista</maintainer>
  <license>BSD-3-Clause</license>

  <exec_depend>rosserial_python</exec_depend>
  <exec_depend>wifi_monitor</exec_depend>
  <exec_depend>kingfisher_twist</exec_depend>
  <exec_depend>kingfisher_viz</exec_depend>
  <exec_depend>kingfisher_sail</exec_depend>
  <exec_depend>kingfisher_teleop</exec_depend>
  <exec_depend>joy_teleop</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>phidgets_digital_inputs</exec_depend>
  <exec_depend>phidgets_high_speed_encoder</exec_depend>
  <exec_depend>phidgets_stepper</exec_depend>
  <exec_depend>kingfisher_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
